def public_pods
    source 'https://github.com/CocoaPods/Specs.git' # 公有源
    
end

def njspec_pods
    # 开发
    #develop_local_pods
    # 发布
    release_remote_pods
end

def develop_local_pods
    
    source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
    
    pod 'NJKit', :path => '../../NJKit/'
    pod 'NJMediator', :path => '../../NJMediator/'
    
    
    pod 'DYTrends', :path => '../../DYTrends/'
    pod 'NJMediator_DYTrends', :path => '../../NJMediator_DYTrends/'
    
    pod 'DYLiveShow', :path => '../../DYLiveShow/'
    pod 'NJMediator_DYLiveShow', :path => '../../NJMediator_DYLiveShow/'
        # DYTrends & DYLiveShow 依赖 NJDYSearchBarView
            pod 'NJDYSearchBarView', :path => '../../NJDYSearchBarView/'
        # DYLiveShow 依赖 DYLiveRoom
        pod 'DYLiveRoom', :path => '../../DYLiveRoom/'
    
    pod 'NJNowShow', :path => '../../NJNowShow/'
    pod 'NJMediator_NJNowShow', :path => '../../NJMediator_NJNowShow/'
    
        # NJNowShow 依赖 NJNowShowPlay
        pod 'NJNowShowPlay', :path => '../../NJNowShowPlay'
                ## NJNowShowPlay 依赖 NJDYPlayer
                pod 'NJDYPlayer', :path => '../../NJDYPlayer'
                ## NJDYPlayer 依赖 NJIJKPlayer
                #pod 'NJIJKPlayer', :path => '../../NJIJKPlayer'

end

def release_remote_pods
    
    source 'https://github.com/NJHu/NJSpecs.git' # NJ 私有源
    
    pod 'NJKit'
    pod 'NJMediator', :source => 'https://github.com/NJHu/NJSpecs.git'
    
    pod 'DYTrends'
    pod 'NJMediator_DYTrends'
    
    pod 'DYLiveShow'
    pod 'NJMediator_DYLiveShow'
    
    pod 'NJNowShow'
    pod 'NJMediator_NJNowShow'
    
end

platform :ios, '10.3'

use_frameworks!

target 'NJDouYu' do
    
    inhibit_all_warnings!
    
    njspec_pods
    
    public_pods
    
    target 'NJDouYuTests' do
        inherit! :search_paths
        
    end
    
    target 'NJDouYuUITests' do
        inherit! :search_paths
        
    end
    
end


# 参考
#pod 'xxx', :git => 'git@xx.com:xx-ios/xx.git', :commit => '1dsafas8769823t1876378'
#pod 'xx', '2.8.8' , :configuration => 'Debug'
#pod 'xx', '2.8.8', :configuration => 'Release'
#pod 'xx','0.1.2'
#pod 'DYTrends', :git => 'https://github.com/njhu/DYTrends.git', :branch => 'master'
#pod 'NJKit', :git => 'https://github.com/njhu/NJKit.git'
