
platform :ios, '10.3'

use_frameworks!

target 'NJDouYu' do

  pod 'Alamofire'
  pod 'Masonry'

  target 'NJDouYuTests' do
    inherit! :search_paths

  end

  target 'NJDouYuUITests' do
    inherit! :search_paths


  end

end
