
platform :ios, '10.3'

use_frameworks!

target 'NJDouYu' do
    
inhibit_all_warnings!

  pod 'Alamofire'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'SDWebImage'

  target 'NJDouYuTests' do
    inherit! :search_paths

  end

  target 'NJDouYuUITests' do
    inherit! :search_paths


  end

end
